# Generated by Django 5.2.17 on 2026-09-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automl_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveIntegerField()),
                ('task_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=16)),
                ('metrics', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_results', to='automl_core.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
